---
- name: Install & Configure Catalogue app
  hosts: catalogue
  become: yes
  tasks:
  - name: Setup NodeJS repos
    shell: 'curl -sL https://rpm.nodesource.com/setup_lts.x | bash'
      
  - name: Install NodeJS
    yum:
      name: nodejs
      state: installed

  - name: Check application User exit or not
    command: id roboshop
    register: user
    ignore_errors: yes
  - name: Add app user
    user:
      name: roboshop
    when: user.rc != 0

  - name: Check an app directory
    stat:
      path: /app
    register: st  
  - name: Create app dir
    file:
      path: /app
      state: directory
    when: st.stat.exists == false

  - name: Download the application code
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /app

  - name: Unzip app code
    unarchive: 
      src: /app/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install npm 
    command: npm install 
    args: 
      chdir: /app

  - name: Setup SystemD Catalogue Service
    copy:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
  

  
      

