---
- name: Install & Configure Catalogue app
  hosts: catalogue
  become: yes
  tasks:
  - name: Setup NodeJS repos
    shell: 'curl -sL https://rpm.nodesource.com/setup_lts.x | bash'
      
  - name: Install NodeJS
    yum:
      name: nodejs
      state: installed

  - name: Check application User exit or not
    command: id roboshop
    register: user
  - name: print user
    debug: 
      var: '{{user}}'