---
- name: Setup Web app
  hosts: web
  become: true
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: installed

  - name: Remove all files under html dir
    file:
      path: '{{ item }}'
      state: absent
    with_fileglob:
      - "/usr/share/nginx/html/*"

  - name: Download code
    get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /usr/share/nginx/html/

  - name: Extract the code
    unarchive: 
      src: /usr/share/nginx/html/web.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: Create Nginx Reverse Proxy Configuration
    tags:
      - proxy_conf
    template:
      src: roboshop.conf.j2
      dest: /etc/nginx/default.d/roboshop.conf

  - name: Restart Nginx Service
    tags:
      - restart_nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

   